import express = require('express');
import controller from '../controllers/controller';
const router = express.Router();

router.get('/utenti', controller.getUtenti);
router.get('/utenti/getTipo/:username', controller.getUtenteTipo);
router.get('/utenti/insert/:username/:password', controller.putUtente);
router.get('/pubblicitari', controller.getPubblicitari);
router.get('/pubblicitari/rimuovi/:username', controller.removePubblicitari);
router.get('/pubblicitari/aggiungi/:username/:password', controller.putPubblicitari);
router.get('/news', controller.getNews);
router.get('/news/rimuovi/:id', controller.removeNews);
router.get('/news/aggiungi/:argomento/:descrizione/:username', controller.putNews);
router.get('/lottatore', controller.getLottatori);
router.get('/lottatore/complete', controller.getFiltedLottatori);
router.get('/lottatore/aggiungi/:nome/:cognome/:cf/:nascita/:peso/:team/:disciplina', controller.putLottatore);
router.get('/lottatore/modifica/:tempLottatore/:tempRecord', controller.editLottatore);
router.get('/lottatore/rimuovi/:cf', controller.deleteLottatore);
router.get('/record/:cf', controller.getRecord);
router.get('/categoria', controller.getCategorie);
router.get('/disciplina', controller.getDiscipline);
router.get('/team', controller.getTeams);
router.get('/team/aggiungi/:TeamName/:CeoName/:Countrie', controller.putTeam);
router.get('/team/rimuovi/:id', controller.deleteTeam);
router.get('/sponsor', controller.getSponsor);
router.get('/sponsor/aggiungi/:nome/:pagamento', controller.putSponsor);
router.get('/sponsor/rimuovi/:id', controller.deleteSponsor);
router.get('/eventi', controller.getEventi);
router.get('/eventi/:id', controller.getEventoSingolo);
router.get('/evento/aggiungi/:evento/:scontroI/:scontroII', controller.putEventoIIScontri);
router.get('/evento/aggiungi/:evento/:scontroI/:scontroII/:scontroIII', controller.putEventoIIIScontri);
router.get('/evento/aggiungi/:evento/:scontroI/:scontroII/:scontroIII/:scontroIV', controller.putEventoIVScontri);
router.get('/evento/aggiungi/:evento/:scontroI/:scontroII/:scontroIII/:scontroVI/:scontroV', controller.putEventoVScontri);
router.get('/scontri/eventi/:id', controller.getScontriEvento);
router.get('/pesoPiuma', controller.getPesoPiuma);
router.get('/welterWeight', controller.getWelterWeight);
router.get('/pesoMedio', controller.getPesoMedio);
router.get('/pesiMassimi', controller.getPesiMassimi);

export = router;